// stripe-webhook — RealtyFlow Systems
// Rewritten to match actual Supabase schema.
// On checkout.session.completed: upsert lead → insert payment → insert client → send onboarding email
//
// Stripe Dashboard → Developers → Webhooks → Add endpoint:
//   URL: https://wufmcymarbkrjzaqapuu.supabase.co/functions/v1/stripe-webhook
//   Events: checkout.session.completed

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const STAGE_CLIENT = 5;
const STAGE_NAME_CLIENT = "Client";

serve(async (req: Request) => {
  const signature     = req.headers.get("stripe-signature");
  const body          = await req.text();
  const webhookSecret = Deno.env.get("STRIPE_WEBHOOK_SECRET")!;

  if (!signature) return new Response("Missing stripe-signature", { status: 400 });

  const valid = await verifyStripeSignature(body, signature, webhookSecret);
  if (!valid) return new Response("Invalid signature", { status: 400 });

  const event = JSON.parse(body);

  if (event.type !== "checkout.session.completed") {
    return new Response(JSON.stringify({ received: true, skipped: true }), { status: 200 });
  }

  const session            = event.data.object;
  const customerEmail      = (session.customer_details?.email ?? session.receipt_email ?? "").toLowerCase();
  const customerName       = session.customer_details?.name ?? "";
  const amountCents        = session.amount_total ?? 0;
  const stripeCustomerId   = session.customer ?? null;
  const stripeSessionId    = session.id;
  const stripePaymentIntent = session.payment_intent ?? null;
  const tier               = session.metadata?.tier ?? session.metadata?.plan ?? null;

  if (!customerEmail) {
    console.warn("No customer email in event", event.id);
    return new Response(JSON.stringify({ received: true }), { status: 200 });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const nameParts = customerName.trim().split(/\s+/);
  const fname     = nameParts[0] ?? "";
  const lname     = nameParts.slice(1).join(" ") || "";

  // Upsert lead → mark as client
  const { data: lead, error: leadErr } = await supabase
    .from("leads")
    .upsert(
      {
        fname,
        lname,
        email: customerEmail,
        stage: STAGE_CLIENT,
        stage_name: STAGE_NAME_CLIENT,
        tier: tier ?? undefined,
      },
      { onConflict: "email" }
    )
    .select()
    .single();

  if (leadErr) {
    console.error("lead upsert:", leadErr);
    return new Response(JSON.stringify({ error: leadErr.message }), { status: 500 });
  }

  // Insert payment record
  const { data: payment, error: paymentErr } = await supabase
    .from("payments")
    .insert({
      lead_id:                    lead.id,
      stripe_payment_intent_id:   stripePaymentIntent,
      stripe_customer_id:         stripeCustomerId,
      stripe_checkout_session_id: stripeSessionId,
      amount_cents:               amountCents,
      currency:                   "usd",
      status:                     "succeeded",
      tier,
      description:                session.metadata?.description ?? tier ?? "RealtyFlow Systems",
    })
    .select()
    .single();

  if (paymentErr) {
    console.error("payment insert:", paymentErr);
    return new Response(JSON.stringify({ error: paymentErr.message }), { status: 500 });
  }

  // Insert client record (portal_token auto-generated by DB default)
  const { data: client, error: clientErr } = await supabase
    .from("clients")
    .insert({
      lead_id:    lead.id,
      payment_id: payment.id,
    })
    .select()
    .single();

  if (clientErr) {
    console.error("client insert:", clientErr);
    return new Response(JSON.stringify({ error: clientErr.message }), { status: 500 });
  }

  // Send onboarding email
  const resendKey = Deno.env.get("RESEND_API_KEY");
  if (resendKey) {
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "RealtyFlow Systems <erics@realtyflow.xyz>",
        to:   [customerEmail],
        subject: "Welcome to RealtyFlow Systems — Your Portal is Ready",
        html:  onboardingEmail(fname, client.portal_token, tier),
      }),
    });

    await supabase.from("emails").insert({
      lead_id:  lead.id,
      subject:  "Welcome to RealtyFlow Systems",
      type:     "transactional",
      sent_at:  new Date().toISOString(),
    });
  }

  // Log activity
  await supabase.from("activity_log").insert({
    lead_id:     lead.id,
    type:        "payment_received",
    description: `Payment of $${(amountCents / 100).toFixed(2)} received — ${tier ?? "RFS"}`,
    metadata:    { payment_id: payment.id, client_id: client.id, stripe_session: stripeSessionId },
  });

  return new Response(JSON.stringify({ received: true, client_id: client.id }), {
    headers: { "Content-Type": "application/json" },
  });
});

// ── Stripe signature verification ──────────────────────────────────────────
async function verifyStripeSignature(payload: string, header: string, secret: string): Promise<boolean> {
  try {
    const parts     = Object.fromEntries(header.split(",").map(p => p.split("=")));
    const timestamp = parts["t"];
    const sig       = parts["v1"];
    const signed    = `${timestamp}.${payload}`;
    const key       = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(secret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"]
    );
    const mac = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(signed));
    const hex = Array.from(new Uint8Array(mac)).map(b => b.toString(16).padStart(2, "0")).join("");
    return hex === sig;
  } catch {
    return false;
  }
}

// ── Onboarding email ───────────────────────────────────────────────────────
function onboardingEmail(fname: string, portalToken: string, tier: string | null): string {
  const portalUrl = `https://realtyflow.xyz/portal?token=${portalToken}`;
  const tierLabel = tier ? tier.charAt(0).toUpperCase() + tier.slice(1) : "RealtyFlow";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/></head>
<body style="background:#0A0A0A;color:#fff;font-family:'Helvetica Neue',Arial,sans-serif;max-width:560px;margin:0 auto;padding:0;">
  <div style="padding:32px 40px;border-bottom:1px solid rgba(201,168,76,.2);">
    <p style="font-size:10px;color:#C9A84C;letter-spacing:.3em;text-transform:uppercase;margin:0 0 8px;">RealtyFlow Systems</p>
    <h1 style="font-size:30px;font-weight:300;margin:0;line-height:1.2;">Welcome,<br><em style="font-style:italic;color:#C9A84C;">${fname}</em></h1>
  </div>
  <div style="padding:32px 40px;">
    <p style="font-size:14px;color:#AAA;line-height:1.75;margin:0 0 8px;">
      Payment confirmed. You're on the <strong style="color:#E0E0E0;">${tierLabel}</strong> plan. Your portal is live.
    </p>
    <div style="margin:28px 0;">
      <a href="${portalUrl}"
         style="display:inline-block;padding:14px 28px;background:#C9A84C;color:#0A0A0A;
                font-size:11px;font-weight:700;letter-spacing:.15em;text-transform:uppercase;text-decoration:none;">
        ACCESS YOUR PORTAL →
      </a>
    </div>
    <p style="font-size:13px;color:#AAA;line-height:1.75;">
      I'll be in touch within 24 hours to schedule your kickoff call. Keep this email — your portal link is unique to your account.
    </p>
    <p style="font-size:13px;color:#AAA;margin-top:16px;">
      Questions? <a href="mailto:erics@realtyflow.xyz" style="color:#C9A84C;text-decoration:none;">erics@realtyflow.xyz</a>
    </p>
  </div>
  <div style="padding:20px 40px;border-top:1px solid rgba(255,255,255,.06);">
    <p style="font-size:11px;color:#444;margin:0;">RealtyFlow Systems · 820 Massachusetts Ave, Cambridge, MA 02139</p>
  </div>
</body>
</html>`;
}
